### PR TITLE
Using the static AppCache class correctly.

### PR DESCRIPTION
**Pull request by jasedit**
Someone on the ServerAPI team please test this build and see if it works/acts as expected.

### CODE REVIEW

**Comment by arjunpassi** [comment]
I can't build it. I get these errors 

Error   70  Metadata file '\vmware-host\Shared Folders\Documents\VTCourses\ECE-5574\Automation_System\Devices\api\bin\Debug\api.dll' could not be found    \vmware-host\Shared Folders\Documents\VTCourses\ECE-5574\Automation_System\Devices\House\CSC   House
Error   77  Metadata file '\vmware-host\Shared Folders\Documents\VTCourses\ECE-5574\Automation_System\Devices\api\bin\Debug\api.dll' could not be found    \vmware-host\Shared Folders\Documents\VTCourses\ECE-5574\Automation_System\Devices\api_tests\CSC   api_tests
Error   74  Metadata file '\vmware-host\Shared Folders\Documents\VTCourses\ECE-5574\Automation_System\MobileApp\HomeAutomationApp\bin\Debug\HomeAutomationApp.dll' could not be found  \vmware-host\Shared Folders\Documents\VTCourses\ECE-5574\Automation_System\MobileApp\LogicUnitTests\CSC    HomeAutomationAppTests
Error   71  Metadata file '\vmware-host\Shared Folders\Documents\VTCourses\ECE-5574\Automation_System\sim_harness\sim_weather\bin\Debug\sim_weather.dll' could not be found    \vmware-host\Shared Folders\Documents\VTCourses\ECE-5574\Automation_System\Devices\House\CSC   House
Error   1   Metadata file '\vmware-host\Shared Folders\Documents\VTCourses\ECE-5574\Automation_System\sim_harness\time_frame\time_frame\bin\Debug\time_frame.dll' could not be found   \vmware-host\Shared Folders\Documents\VTCourses\ECE-5574\Automation_System\Devices\api\CSC api
Error   72  Metadata file '\vmware-host\Shared Folders\Documents\VTCourses\ECE-5574\Automation_System\sim_harness\time_frame\time_frame\bin\Debug\time_frame.dll' could not be found   \vmware-host\Shared Folders\Documents\VTCourses\ECE-5574\Automation_System\Devices\House\CSC   House
Error   78  Metadata file '\vmware-host\Shared Folders\Documents\VTCourses\ECE-5574\Automation_System\sim_harness\time_frame\time_frame\bin\Debug\time_frame.dll' could not be found   \vmware-host\Shared Folders\Documents\VTCourses\ECE-5574\Automation_System\Devices\api_tests\CSC   api_tests

**Comment by jasedit** [comment]
The CSC strings everywhere seem weird - it's suggesting something is injecting bogus paths everywhere. Can you find anything on disk or in the project referencing CSC?

Also, are you building on Visual Studio or Xamarin?

**Comment by arjunpassi** [comment]
I am using Visual Studio and no I can't find anything referencing to CSC.

**Comment by jasedit** [comment]
Can you find any of those .dll's on the disk, but without the CSC statement? IOW, does `\vmware-host\Shared Folders\Documents\VTCourses\ECE5574\Automation_System\Devices\api\bin\Debug\api.dll` exist?

Also, the HomeAutomationServer currently doesn't reference the api DLL, time_frame, or sim_weather. Those errors are suggesting something else is broken, not necessarily the HomeAutomationServer. Which part of the system are you attempting to build?

I'm trying to figure out if this is a partial build error, references being broken, or something else.

**Comment by jasedit** [comment]
According to [Travis](https://travis-ci.org/ECE4574-5574/Automation_System/builds/59174441), this builds correctly now, although the LogicUnitTests fail.

**Comment by jasedit** [comment]
Sigh. This PR has been obviated by commits which have been pushed directly to master.

**Pull request closed without merging**
